### ISSUE TITLE
Light group names

### ISSUE THREAD

**Issue by ghost** [sarkonovich/Alexa-Hue#4]
Hey Steve,

I'm Raul btw... we've been going back and forth a bit on Reddit.

So one of the things that I like is to make the echo commands as short and natural as possible. (if I can shave a syllable off of a command, I'm happy)

With that, I want to be able to use this skill to say a command like "tell phillip to turn the lights blue"/

The problem is that the skill as is, expects to hear a group name before the "lights" keyword, and the command fails with the "I couldn't find a group with the name" ... response.

I think there should be an option to designate a DEFAULT light group name, that you fall back to if (and only if) the user does not specify any group name. This would let people speak more naturally to the echo...

**Comment by sarkonovich** [comment]
Hey there!

Thanks for your input. It's been really helpful.

This is a good idea. Right now, the program checks to see if there's an
existing group/light/scene name matching what you asked for. So, if you
leave off a group name, it fails the check. (I just have a group called
"house"...so, "turn off the house lights.")

It would be easy to change the program so that if you don't specify a group
it defaults to all the lights. It would be harder to set it up so that the
user can specify a default group, but probably the first option is most
natural, i.e, "turn off the lights" means turn them all off.

I'll do that. Just check back on the repo between 5 minutes from now...and
tomorrow!

Steve

**Comment by sarkonovich** [comment]
If group isn't specified for action, defaults to all lights.

If user only has one light, there is no longer a need to name it (e.g., "turn off the light" will work). If user has multiple lights and requests action on single, unspecified light, user is prompted to specify which one action should be taken on.
